# This file describes the keymaps that will be built by the GitHub Actions CI.

include:
  - board: qmx2040
    artifact-name: qmx2040
    snippet: zmk-usb-logging
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y
